const express = require("express");
const router = express.Router();
const { verifyToken } = require("../middleware/authMiddleware");
const tournamentController = require("../controllers/tournamentController");
const asyncHandler = require("../utils/asyncHandler");
const {
  validateTournamentInput,
  checkTournamentExists,
  checkTournamentDirector,
} = require("../middleware/tournamentMiddleware");

const authTournamentMiddleware = [verifyToken, checkTournamentExists];
const directorTournamentMiddleware = [
  ...authTournamentMiddleware,
  checkTournamentDirector,
];

router.get("/", asyncHandler(tournamentController.getAllTournaments));

router.get(
  "/:id",
  checkTournamentExists,
  asyncHandler(tournamentController.getTournamentById)
);

router.get(
  "/:id/teams",
  ...authTournamentMiddleware,
  asyncHandler(tournamentController.getTournamentTeams)
);

router.get(
  "/:id/divisions",
  checkTournamentExists,
  asyncHandler(tournamentController.getTournamentDivisions)
);

router.post(
  "/:id/divisions",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.createTournamentDivision)
);

router.get(
  "/:id/divisions/:divisionId/pools",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.getDivisionPools)
);

router.post(
  "/:id/divisions/:divisionId/pools/generate",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.generateDivisionPoolsSnake)
);

router.post(
  "/:id/divisions/:divisionId/matches/auto-generate",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.autoGenerateDivisionPoolMatches)
);

router.get(
  "/:id/registrations",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.getTournamentRegistrations)
);

router.patch(
  "/:id/registrations/reorder",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.reorderTournamentRegistrations)
);

router.patch(
  "/:id/registrations/:registrationId",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.updateTournamentRegistration)
);

router.get(
  "/:id/details",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.getTournamentDetails)
);

router.post(
  "/",
  verifyToken,
  validateTournamentInput,
  asyncHandler(tournamentController.createTournament)
);

router.put(
  "/:id",
  ...directorTournamentMiddleware,
  validateTournamentInput,
  asyncHandler(tournamentController.updateTournament)
);

router.delete(
  "/:id",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.deleteTournament)
);

router.post(
  "/:id/register",
  ...authTournamentMiddleware,
  asyncHandler(tournamentController.registerForTournament)
);

router.delete(
  "/:id/unregister",
  verifyToken,
  asyncHandler(tournamentController.unregisterFromTournament)
);

router.get(
  "/:id/matches/candidates",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.getTournamentMatchCandidates)
);

router.get(
  "/:id/matches",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.getTournamentMatches)
);

router.post(
  "/:id/matches",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.createTournamentMatch)
);

router.patch(
  "/:id/matches/:matchId",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.updateTournamentMatch)
);

router.post(
  "/:id/matches/:matchId/results",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.saveTournamentMatchResults)
);

router.get(
  "/:id/stats",
  ...directorTournamentMiddleware,
  asyncHandler(tournamentController.getTournamentOutcomeStats)
);

router.get(
  "/:id/my-match-alerts",
  ...authTournamentMiddleware,
  asyncHandler(tournamentController.getMyMatchAlerts)
);

module.exports = router;
